Style/FrozenStringLiteralComment:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/StringLiterals:
  Enabled: false