 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/semafors", type: :request do
  # Semafor. As you add validations to Semafor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Semafor.create! valid_attributes
      get semafors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      semafor = Semafor.create! valid_attributes
      get semafor_url(semafor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_semafor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      semafor = Semafor.create! valid_attributes
      get edit_semafor_url(semafor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Semafor" do
        expect {
          post semafors_url, params: { semafor: valid_attributes }
        }.to change(Semafor, :count).by(1)
      end

      it "redirects to the created semafor" do
        post semafors_url, params: { semafor: valid_attributes }
        expect(response).to redirect_to(semafor_url(Semafor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Semafor" do
        expect {
          post semafors_url, params: { semafor: invalid_attributes }
        }.to change(Semafor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post semafors_url, params: { semafor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested semafor" do
        semafor = Semafor.create! valid_attributes
        patch semafor_url(semafor), params: { semafor: new_attributes }
        semafor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the semafor" do
        semafor = Semafor.create! valid_attributes
        patch semafor_url(semafor), params: { semafor: new_attributes }
        semafor.reload
        expect(response).to redirect_to(semafor_url(semafor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        semafor = Semafor.create! valid_attributes
        patch semafor_url(semafor), params: { semafor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested semafor" do
      semafor = Semafor.create! valid_attributes
      expect {
        delete semafor_url(semafor)
      }.to change(Semafor, :count).by(-1)
    end

    it "redirects to the semafors list" do
      semafor = Semafor.create! valid_attributes
      delete semafor_url(semafor)
      expect(response).to redirect_to(semafors_url)
    end
  end
end
